name: Java CI with Maven
on:
  push:
    branches: ["main"]
    
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Step 01. Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven  

      - name: Set Environment Variable
        run: export ARCH=x86_64 

      - name: Check Architecture
        run: uname -m
        
      - name: Step 02. Build with Maven 
        run: mvn clean package
      

      - name: Step 03. Run tests 
        run: mvn test
  
      - name: Step 04. Deploy
        run: mkdir staging && cp target/*.jar staging  

      - name: Set Executable Permissions
        run: chmod +x target/testing-2024-1.0-SNAPSHOT.jar 
        
      - name: Step 05. Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: javiergs-app
          path: target/testing-2024-1.0-SNAPSHOT.jar  
      
      - name: Step 06. Just for Fun an LS
        run: ls -al target


    #  - name: Step 07. Create macOS App with JPackage
    #    run: |
    #      jpackage --input target \
    #               --name MyApp \
    #               --main-jar testing-2024-1.0-SNAPSHOT.jar \
    #               --main-class javiergs.main \
    #               --type app-image \
    #               --icon src/main/resources/jgs-icon.icns
    #    
    #  - name: Step 08. Just for Fun an LS
    #    run: ls -al ./

    # - name: Compress Application Bundle
    #    run: zip -r MyApp.zip MyApp.app 
  
    #  - name: Step 09. Upload macOS Artifact
    #    uses: actions/upload-artifact@v4
    #    with:
    #      name: my-macos-app
    #      path: MyApp.zip 


      - name: Create GitHub Release
        id: create_release  # Assign an ID to this step to reference the release later
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}  # Use the pushed tag name for the release
          release_name: Release ${{ github.ref_name }}  # Optional: Release title
          body: "Description of the release"
          draft: false  # Set to true if you want a draft release
          prerelease: false  # Set to true for a prerelease
  
      - name: Upload Artifacts to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # Use the URL from create-release
          asset_path: target/testing-2024-1.0-SNAPSHOT.jar  # Replace with your artifact's path
          asset_name: my-artifact.jar  # Name of the artifact on the release
          asset_content_type: application/java-archive  # Set the correct MIME type
         
