# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Java Package Published with Maven 

on:
  release:
    types: [created]

jobs:
  build:
  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
       # server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
       # settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn clean package 

    - name: Publish to GitHub Packages Apache Maven
      #run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      run: mvn deploy -s $GITHUB_WORKSPACE

    #- name: Upload Artifacts to Release
    #  uses: actions/upload-release-asset@v1
    #  env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    #    upload_url: ${{ steps.create_release.outputs.upload_url }}
    #    asset_path: target/testing-2024-1.0-SNAPSHOT.jar  # Replace with your artifact's path
    #    asset_name: my-artifact.jar  # Name of the artifact on the release
    #    asset_content_type: application/java-archive  # Set the correct MIME type
