name: Java CI with Maven
on:
  push:
    branches: ["main"]
    
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Step 01. Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven  

      - name: Set Environment Variable
        run: export ARCH=x86_64 

      - name: Check Architecture
        run: uname -m
        
      - name: Step 02. Build with Maven 
        run: mvn clean package
      

      - name: Step 03. Run tests 
        run: mvn test
  
      - name: Step 04. Deploy
        run: mkdir staging && cp target/*.jar staging  

      - name: Set Executable Permissions
        run: chmod +x target/testing-2024-1.0-SNAPSHOT.jar 
        
      - name: Step 05. Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: javiergs-app
          path: target/testing-2024-1.0-SNAPSHOT.jar  
      
      - name: Step 06. Just for Fun an LS
        run: ls -al target


    #  - name: Step 07. Create macOS App with JPackage
    #    run: |
    #      jpackage --input target \
    #               --name MyApp \
    #               --main-jar testing-2024-1.0-SNAPSHOT.jar \
    #               --main-class javiergs.main \
    #               --type app-image \
    #               --icon src/main/resources/jgs-icon.icns
    #    
    #  - name: Step 08. Just for Fun an LS
    #    run: ls -al ./

    # - name: Compress Application Bundle
    #    run: zip -r MyApp.zip MyApp.app 
  
    #  - name: Step 09. Upload macOS Artifact
    #    uses: actions/upload-artifact@v4
    #    with:
    #      name: my-macos-app
    #      path: MyApp.zip 

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          retention-days: 1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.YOUR-GITHUB-TOKEN }}"
          automatic_release_tag: "${{ github.run_number }}"
          title: "Automated Build ${{ github.run_number }}"
          prerelease: true
          files: staging/*.jar
          
