name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven  

      - name: Build with Maven 
        run: mvn -B clean package --file pom.xml  # Include 'clean' to ensure a fresh build

      - name: Run tests 
        run: mvn test
        
      - name: Deploy
        run: mkdir staging && cp target/*.jar staging  # Creates the directory and copies the JARs
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: javiergs-app
          path: staging 
